#include "game_arena/server/generated_build.h"

#include <algorithm>
#include <sstream>
#include <string_view>

namespace tournament_arena {

namespace {

// Sorts and de-duplicates all but the first entry, the harness dep.
void NormalizeDeps(std::vector<std::string> *deps) {
  std::sort(deps->begin() + 1, deps->end());
  deps->erase(std::unique(deps->begin(), deps->end()), deps->end());
}

}  // namespace

std::string GenerateCandidateBuild(const proto::CandidateHarness &harness,
                                   const std::vector<std::string> &file_paths,
                                   const std::string &entry_header,
                                   const std::vector<std::string> &extra_deps) {
  if (file_paths.empty() || entry_header.empty()) {
    return {};
  }
  if (std::find(file_paths.begin(), file_paths.end(), entry_header) ==
      file_paths.end()) {
    return {};
  }
  if (harness.api_dep().empty() || harness.main_src().empty()) {
    return {};
  }
  const std::string &game_define = harness.game_define();

  std::vector<std::string> headers;
  std::vector<std::string> sources;
  for (const std::string &path : file_paths) {
    // Anything else was already rejected by the store's extension allowlist.
    (path.ends_with(".cc") || path.ends_with(".cpp") ? sources : headers)
        .push_back(path);
  }
  std::sort(headers.begin(), headers.end());
  std::sort(sources.begin(), sources.end());

  std::vector<std::string> strategy_deps = {harness.api_dep()};
  strategy_deps.insert(strategy_deps.end(), extra_deps.begin(),
                       extra_deps.end());
  NormalizeDeps(&strategy_deps);

  std::vector<std::string> bot_deps = {":strategy", harness.api_dep()};
  bot_deps.insert(bot_deps.end(), harness.bot_deps().begin(),
                  harness.bot_deps().end());
  NormalizeDeps(&bot_deps);

  std::ostringstream build;
  const auto list = [&build](std::string_view name,
                             const std::vector<std::string> &items) {
    build << "    " << name << " = [\n";
    for (const std::string &item : items) {
      build << "        \"" << item << "\",\n";
    }
    build << "    ],\n";
  };
  build << "# Generated by the arena at submit time.\n"
           "# Do not edit: it is part of the submission's patch.\n\n"
           "load(\"@rules_cc//cc:cc_binary.bzl\", \"cc_binary\")\n"
           "load(\"@rules_cc//cc:cc_library.bzl\", \"cc_library\")\n\n"
           "package(default_visibility = [\"//visibility:private\"])\n\n"
           "cc_library(\n"
           "    name = \"strategy\",\n";
  list("hdrs", headers);
  if (!sources.empty()) {
    list("srcs", sources);
  }
  list("deps", strategy_deps);
  if (!game_define.empty()) {
    build << "    local_defines = [\"" << game_define << "\"],\n";
  }
  build << ")\n\n";

  // main is compiled here: local_defines do not reach a prebuilt library.
  build << "cc_binary(\n"
        << "    name = \""
        << (harness.binary_name().empty() ? "bot" : harness.binary_name())
        << "\",\n"
        << "    srcs = [\"" << harness.main_src() << "\"],\n"
        << "    local_defines = [\n"
        << "        r'CANDIDATE_ENTRY_HEADER=\\\"' + package_name() + r'/"
        << entry_header << "\\\"',\n";
  if (!game_define.empty()) {
    build << "        \"" << game_define << "\",\n";
  }
  build << "    ],\n";
  list("deps", bot_deps);
  build << ")\n";
  return build.str();
}

}  // namespace tournament_arena
